export const SOCKET_CONNECT_START = "USER_CONNECT_START";
export const SOCKET_CONNECT_SUCCESS = "USER_CONNECT_SUCCESS";
export const SOCKET_CONNECT_ERROR = "USER_CONNECT_ERROR";

export const PRICE_MESSAGE = "PRICE_MESSAGE";
export const SUBSCRIPTIONS_MESSAGE = "SUBSCRIPTIONS_MESSAGE";
